[project]
name = "jetlag-private"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.20.0",
    "mapclassify>=2.10.0",
    "osmnx>=2.1.0",
    "resplotlib",
]


[tool.uv.sources]
resplotlib = { git = "https://github.com/Ruben-White/resplotlib.git", rev = "main" }
